[package]
name = "util"
version = "0.10.0"
authors = ["Mile Davidovic <mile.davidovic@gmail.com>"]
edition = "2024"
keywords = ["rmore", "rvi", "hex", "bmore", "bvi"]
categories = ["command-line-utilities"]